### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by danmartinez101** [sprintly/sprintly-kanban#65]
The readme lists "Sprint.ly API running on https://local.sprint.ly:9000/" as a prerequisite, but I can't find any information on how to get that running. 

Additionally, running the app seems to require a PUSHER_KEY to be set as an environment variable but there is no reference to appropriate values that I can find.

Can you direct me towards figuring out how to run this locally?

p.s. Thank you a million times for releasing this project! I've been searching periodically over the last few months for a non-trivial application built with react and flux and I'm sure I'm not the only person in this boat. You all rock! :)

**Comment by wookiehangover** [comment]
@danmartinez101 thanks for opening an issue!

Right now, there are a few things we're working on to enable people to develop on this locally:

1. A public facing Oauth settings page in the main app — in order to develop locally, you'll need to manage OAuth credentials and set up an API client for developing locally.
2. A strategy for granting Pusher access without sharing sensitive keys. Unfortunately, we're presently unable to offer realtime features for local development, since the backend socket connection is brokered through Pusher. We're working with Pusher to figure out a strategy for local development that doesn't involve sharing credentials.

Fortunately, Pusher is not a *strict* requirement for local development, but you will miss out on some realtime syncing features.

In the meantime, please follow the instructions in your support email thread for running Kanban with https://sprint.ly and let us know if you run into any issues.
